logging.level.ru.yandex.practicum.filmorate=DEBUG
logging.level.org.zalando.logbook: DEBUG
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=DEBUG
#spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always
spring.datasource.url=jdbc:h2:file:./db/filmorate;TRACE_LEVEL_FILE=4
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create
#spring.profiles.active=db